// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	models "github.com/sunr3d/subscription-aggregator/models"

	services "github.com/sunr3d/subscription-aggregator/internal/interfaces/services"
)

// SubscriptionService is an autogenerated mock type for the SubscriptionService type
type SubscriptionService struct {
	mock.Mock
}

type SubscriptionService_Expecter struct {
	mock *mock.Mock
}

func (_m *SubscriptionService) EXPECT() *SubscriptionService_Expecter {
	return &SubscriptionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, data
func (_m *SubscriptionService) Create(ctx context.Context, data models.Subscription) (int, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription) (int, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription) int); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Subscription) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SubscriptionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.Subscription
func (_e *SubscriptionService_Expecter) Create(ctx interface{}, data interface{}) *SubscriptionService_Create_Call {
	return &SubscriptionService_Create_Call{Call: _e.mock.On("Create", ctx, data)}
}

func (_c *SubscriptionService_Create_Call) Run(run func(ctx context.Context, data models.Subscription)) *SubscriptionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Subscription))
	})
	return _c
}

func (_c *SubscriptionService_Create_Call) Return(_a0 int, _a1 error) *SubscriptionService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionService_Create_Call) RunAndReturn(run func(context.Context, models.Subscription) (int, error)) *SubscriptionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SubscriptionService) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SubscriptionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *SubscriptionService_Expecter) Delete(ctx interface{}, id interface{}) *SubscriptionService_Delete_Call {
	return &SubscriptionService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SubscriptionService_Delete_Call) Run(run func(ctx context.Context, id int)) *SubscriptionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *SubscriptionService_Delete_Call) Return(_a0 error) *SubscriptionService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionService_Delete_Call) RunAndReturn(run func(context.Context, int) error) *SubscriptionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *SubscriptionService) GetByID(ctx context.Context, id int) (models.Subscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (models.Subscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) models.Subscription); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Subscription)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type SubscriptionService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *SubscriptionService_Expecter) GetByID(ctx interface{}, id interface{}) *SubscriptionService_GetByID_Call {
	return &SubscriptionService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *SubscriptionService_GetByID_Call) Run(run func(ctx context.Context, id int)) *SubscriptionService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *SubscriptionService_GetByID_Call) Return(_a0 models.Subscription, _a1 error) *SubscriptionService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionService_GetByID_Call) RunAndReturn(run func(context.Context, int) (models.Subscription, error)) *SubscriptionService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *SubscriptionService) List(ctx context.Context, filter services.ListFilter) ([]models.Subscription, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListFilter) ([]models.Subscription, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListFilter) []models.Subscription); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscriptionService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type SubscriptionService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter services.ListFilter
func (_e *SubscriptionService_Expecter) List(ctx interface{}, filter interface{}) *SubscriptionService_List_Call {
	return &SubscriptionService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *SubscriptionService_List_Call) Run(run func(ctx context.Context, filter services.ListFilter)) *SubscriptionService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ListFilter))
	})
	return _c
}

func (_c *SubscriptionService_List_Call) Return(_a0 []models.Subscription, _a1 error) *SubscriptionService_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SubscriptionService_List_Call) RunAndReturn(run func(context.Context, services.ListFilter) ([]models.Subscription, error)) *SubscriptionService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, data
func (_m *SubscriptionService) Update(ctx context.Context, data models.Subscription) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Subscription) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SubscriptionService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SubscriptionService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.Subscription
func (_e *SubscriptionService_Expecter) Update(ctx interface{}, data interface{}) *SubscriptionService_Update_Call {
	return &SubscriptionService_Update_Call{Call: _e.mock.On("Update", ctx, data)}
}

func (_c *SubscriptionService_Update_Call) Run(run func(ctx context.Context, data models.Subscription)) *SubscriptionService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Subscription))
	})
	return _c
}

func (_c *SubscriptionService_Update_Call) Return(_a0 error) *SubscriptionService_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SubscriptionService_Update_Call) RunAndReturn(run func(context.Context, models.Subscription) error) *SubscriptionService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSubscriptionService creates a new instance of SubscriptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionService {
	mock := &SubscriptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
